Data:
  Driver: 'com.mysql.jdbc.Driver'
  DbType: 'mysql'
  Host: 'localhost'
  Port: 3306
  Username: 'root'
  Password: 'asd123456'
  Database: 'plugin'
  Table: 'iConomy'
  initialPoolSize: 2
  maxIdleTime: 30
  maxPoolSize: 10
  minPoolSize: 3
Messages:
  Help:
    - '/money set [name] [amount] - 设置一个账户的金钱数量'
    - '对应权限：money.accounts.set'
    - '/money take [name] [amount] - 扣除一个账户的金钱数量(不加自己的)'
    - '对应权限：money.accounts.take'
    - '/money give [name] [amount] - 增加一个账户的金钱数量(不扣自己的)'
    - '对应权限：money.accounts.give'
    - '/money pay [name] [amount] - 转账给别人'
    - '对应权限：money.payment'
    - '/money help (command) - 查看指令和帮助'
    - '对应权限：money.help'
    - '/money  [name] - 查看别人有多少钱'
    - '对应权限：money.holdings.others'
    - '/money  - 查看自己有多少钱'
    - '对应权限：money.holdings'
  money: "你有"
ThreadPeroid: 60